[project]
name = "{project_name}"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">={python_version}"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
